version: '3'
services:

  app:
    build:
      context: ./
    container_name: monod
    volumes:
      - ../../:/app
    networks:
      - fortress
    labels:
      - "traefik.frontend.rule=Host:monod.mbiz.io"
      - "traefik.port=3000"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=https"

networks:
  fortress:
    external:
      name: fortress_web

